import { Hono } from "hono";
import { serveStatic } from "hono/deno";

const app = new Hono();

// Serve static files from the "dist" directory generated by Vite
app.use("/*", serveStatic({ root: "./dist" }));

export default app;
