name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Type Check
        run: deno task compile

      - name: Unit Test
        run: deno task test:coverage

      - name: Lint
        run: deno task lint

      - name: Vulnerability
        run: deno audit

      - name: Upload Coverage
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build Application
        run: deno task build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist-preview
          path: dist/
          retention-days: 7

      - name: Install Playwright Browsers
        run: deno run -A npm:playwright install --with-deps chromium

      - name: UI Test
        run: deno run -A npm:playwright test playwright_tests/

  deploy-pages:
    needs: [tests, playwright-tests]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build Application
        run: deno task build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
